### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by matheo** [SEscobedo/artastra#1]
Thanks for this @SEscobedo!
are you planning to setup a demo?
Kind regards!

**Comment by SEscobedo** [comment]
Thanks @matheo 
Yes, I hope a demo will be soon available.
I'll add soon more issues and info files to make a collaboration possible.

**Comment by matheo** [comment]
Awesome! thanks!

**Comment by matheo** [comment]
Hola Salvador!
Podemos hacer una llamada en español?
por Meetup, Zoom o el medio que prefieras.

**Comment by SEscobedo** [comment]
Hola Mateo! Claro, tú dime a que hora y cuándo.

**Comment by matheo** [comment]
Puedes mañana en la tarde? escoge la hora, mi timezone es GMT-5

**Comment by SEscobedo** [comment]
mañana 14 horas (GTM-5) está bien?

**Comment by matheo** [comment]
Si, acá está mi correo: me@matheo.co
